package org.nodex.android.activity;
import android.app.Activity;
import org.nodex.android.AndroidComponent;
import org.nodex.android.StartupFailureActivity;
import org.nodex.android.account.SetupActivity;
import org.nodex.android.account.SetupFragment;
import org.nodex.android.account.UnlockActivity;
import org.nodex.android.blog.BlogActivity;
import org.nodex.android.blog.BlogFragment;
import org.nodex.android.blog.BlogPostFragment;
import org.nodex.android.blog.FeedFragment;
import org.nodex.android.blog.ReblogActivity;
import org.nodex.android.blog.ReblogFragment;
import org.nodex.android.blog.RssFeedActivity;
import org.nodex.android.blog.RssFeedDeleteFeedDialogFragment;
import org.nodex.android.blog.RssFeedImportFailedDialogFragment;
import org.nodex.android.blog.RssFeedImportFragment;
import org.nodex.android.blog.RssFeedManageFragment;
import org.nodex.android.blog.WriteBlogPostActivity;
import org.nodex.android.contact.ContactListFragment;
import org.nodex.android.contact.add.nearby.AddNearbyContactActivity;
import org.nodex.android.contact.add.nearby.AddNearbyContactErrorFragment;
import org.nodex.android.contact.add.nearby.AddNearbyContactFragment;
import org.nodex.android.contact.add.nearby.AddNearbyContactIntroFragment;
import org.nodex.android.contact.add.remote.AddContactActivity;
import org.nodex.android.contact.add.remote.LinkExchangeFragment;
import org.nodex.android.contact.add.remote.NicknameFragment;
import org.nodex.android.contact.add.remote.PendingContactListActivity;
import org.nodex.android.contact.connect.ConnectViaBluetoothActivity;
import org.nodex.android.conversation.AliasDialogFragment;
import org.nodex.android.conversation.ConversationActivity;
import org.nodex.android.conversation.ConversationSettingsDialog;
import org.nodex.android.conversation.ImageActivity;
import org.nodex.android.conversation.ImageFragment;
import org.nodex.android.forum.CreateForumActivity;
import org.nodex.android.forum.ForumActivity;
import org.nodex.android.forum.ForumListFragment;
import org.nodex.android.fragment.ScreenFilterDialogFragment;
import org.nodex.android.hotspot.HotspotActivity;
import org.nodex.android.introduction.ContactChooserFragment;
import org.nodex.android.introduction.IntroductionActivity;
import org.nodex.android.introduction.IntroductionMessageFragment;
import org.nodex.android.login.ChangePasswordActivity;
import org.nodex.android.login.OpenDatabaseFragment;
import org.nodex.android.login.PasswordFragment;
import org.nodex.android.login.StartupActivity;
import org.nodex.android.mailbox.MailboxActivity;
import org.nodex.android.navdrawer.NavDrawerActivity;
import org.nodex.android.navdrawer.TransportsActivity;
import org.nodex.android.panic.PanicPreferencesActivity;
import org.nodex.android.panic.PanicResponderActivity;
import org.nodex.android.privategroup.conversation.GroupActivity;
import org.nodex.android.privategroup.creation.CreateGroupActivity;
import org.nodex.android.privategroup.creation.CreateGroupFragment;
import org.nodex.android.privategroup.creation.CreateGroupModule;
import org.nodex.android.privategroup.creation.GroupInviteActivity;
import org.nodex.android.privategroup.creation.GroupInviteFragment;
import org.nodex.android.privategroup.invitation.GroupInvitationActivity;
import org.nodex.android.privategroup.invitation.GroupInvitationModule;
import org.nodex.android.privategroup.list.GroupListFragment;
import org.nodex.android.privategroup.memberlist.GroupMemberListActivity;
import org.nodex.android.privategroup.memberlist.GroupMemberModule;
import org.nodex.android.privategroup.reveal.GroupRevealModule;
import org.nodex.android.privategroup.reveal.RevealContactsActivity;
import org.nodex.android.privategroup.reveal.RevealContactsFragment;
import org.nodex.android.removabledrive.RemovableDriveActivity;
import org.nodex.android.reporting.CrashFragment;
import org.nodex.android.reporting.CrashReportActivity;
import org.nodex.android.reporting.ReportFormFragment;
import org.nodex.android.settings.ConfirmAvatarDialogFragment;
import org.nodex.android.settings.SettingsActivity;
import org.nodex.android.settings.SettingsFragment;
import org.nodex.android.sharing.BlogInvitationActivity;
import org.nodex.android.sharing.BlogSharingStatusActivity;
import org.nodex.android.sharing.ForumInvitationActivity;
import org.nodex.android.sharing.ForumSharingStatusActivity;
import org.nodex.android.sharing.ShareBlogActivity;
import org.nodex.android.sharing.ShareBlogFragment;
import org.nodex.android.sharing.ShareForumActivity;
import org.nodex.android.sharing.ShareForumFragment;
import org.nodex.android.sharing.SharingModule;
import org.nodex.android.splash.SplashScreenActivity;
import org.nodex.android.test.TestDataActivity;
import dagger.Component;
@ActivityScope
@Component(modules = {
		ActivityModule.class,
		CreateGroupModule.class,
		GroupInvitationModule.class,
		GroupMemberModule.class,
		GroupRevealModule.class,
		SharingModule.SharingLegacyModule.class
}, dependencies = AndroidComponent.class)
public interface ActivityComponent {
	Activity activity();
	void inject(SplashScreenActivity activity);
	void inject(StartupActivity activity);
	void inject(SetupActivity activity);
	void inject(NavDrawerActivity activity);
	void inject(PanicResponderActivity activity);
	void inject(PanicPreferencesActivity activity);
	void inject(AddNearbyContactActivity activity);
	void inject(ConversationActivity activity);
	void inject(ImageActivity activity);
	void inject(ForumInvitationActivity activity);
	void inject(BlogInvitationActivity activity);
	void inject(CreateGroupActivity activity);
	void inject(GroupActivity activity);
	void inject(GroupInviteActivity activity);
	void inject(GroupInvitationActivity activity);
	void inject(GroupMemberListActivity activity);
	void inject(RevealContactsActivity activity);
	void inject(CreateForumActivity activity);
	void inject(ShareForumActivity activity);
	void inject(ShareBlogActivity activity);
	void inject(ForumSharingStatusActivity activity);
	void inject(BlogSharingStatusActivity activity);
	void inject(ForumActivity activity);
	void inject(BlogActivity activity);
	void inject(WriteBlogPostActivity activity);
	void inject(BlogFragment fragment);
	void inject(BlogPostFragment fragment);
	void inject(ReblogFragment fragment);
	void inject(ReblogActivity activity);
	void inject(SettingsActivity activity);
	void inject(TransportsActivity activity);
	void inject(TestDataActivity activity);
	void inject(ChangePasswordActivity activity);
	void inject(IntroductionActivity activity);
	void inject(RssFeedActivity activity);
	void inject(StartupFailureActivity activity);
	void inject(UnlockActivity activity);
	void inject(AddContactActivity activity);
	void inject(PendingContactListActivity activity);
	void inject(CrashReportActivity crashReportActivity);
	void inject(HotspotActivity hotspotActivity);
	void inject(RemovableDriveActivity activity);
	void inject(SetupFragment fragment);
	void inject(PasswordFragment imageFragment);
	void inject(OpenDatabaseFragment activity);
	void inject(ContactListFragment fragment);
	void inject(CreateGroupFragment fragment);
	void inject(GroupListFragment fragment);
	void inject(GroupInviteFragment fragment);
	void inject(RevealContactsFragment activity);
	void inject(ForumListFragment fragment);
	void inject(FeedFragment fragment);
	void inject(AddNearbyContactIntroFragment fragment);
	void inject(AddNearbyContactFragment fragment);
	void inject(LinkExchangeFragment fragment);
	void inject(NicknameFragment fragment);
	void inject(ContactChooserFragment fragment);
	void inject(ShareForumFragment fragment);
	void inject(ShareBlogFragment fragment);
	void inject(IntroductionMessageFragment fragment);
	void inject(SettingsFragment fragment);
	void inject(ScreenFilterDialogFragment fragment);
	void inject(AddNearbyContactErrorFragment fragment);
	void inject(AliasDialogFragment aliasDialogFragment);
	void inject(ImageFragment imageFragment);
	void inject(ReportFormFragment reportFormFragment);
	void inject(CrashFragment crashFragment);
	void inject(ConfirmAvatarDialogFragment fragment);
	void inject(ConversationSettingsDialog dialog);
	void inject(RssFeedImportFragment fragment);
	void inject(RssFeedManageFragment fragment);
	void inject(RssFeedImportFailedDialogFragment fragment);
	void inject(RssFeedDeleteFeedDialogFragment fragment);
	void inject(ConnectViaBluetoothActivity connectViaBluetoothActivity);
	void inject(MailboxActivity mailboxActivity);
}